webtalk_init -webtalk_dir C:/Users/davle/Documents/UBA/CESE/CLP/Codigos/clp_tp-FPGA/NCO/synth/NCO.sim/sim_1/behav/xsim/xsim.dir/NCO_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Aug 11 13:04:03 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2244ab0d-d73e-4d87-85f0-68bd8539c78e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "49ad63c6383e4074bbf56a0a92ccad92" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7730U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1996 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7660_KB" -context "xsim\\usage"
webtalk_transmit -clientid 60075899 -regid "" -xml C:/Users/davle/Documents/UBA/CESE/CLP/Codigos/clp_tp-FPGA/NCO/synth/NCO.sim/sim_1/behav/xsim/xsim.dir/NCO_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/davle/Documents/UBA/CESE/CLP/Codigos/clp_tp-FPGA/NCO/synth/NCO.sim/sim_1/behav/xsim/xsim.dir/NCO_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/davle/Documents/UBA/CESE/CLP/Codigos/clp_tp-FPGA/NCO/synth/NCO.sim/sim_1/behav/xsim/xsim.dir/NCO_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
